#!/bin/sh
apt-get -y update 
apt-get -y upgrade
apt-get -y install apache2

echo '<html>
   <head>
      <title>Serveur de Kevin</title>
   </head>
   <body>

        <p>hostname is: $(hostname)</p>
        <p><img src=https://storage.googleapis.com/bucket_1_kevin_sdv/supdevinci-logo.png ></p>

   </body>
</html>
' | sudo tee /var/www/html/index.html
